name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build
        run: |
          # 1. Cria o projeto Flutter padrão
          flutter create temp_app
          
          # 2. Apaga o main.dart padrão
          rm temp_app/lib/main.dart
          
          # 3. Copia o SEU main.dart para dentro da pasta lib do projeto criado
          # Como o seu arquivo está em 'lib/main.dart' na raiz, copiamos ele
          cp lib/main.dart temp_app/lib/main.dart
          
          # 4. Compila usando o ambiente criado
          cd temp_app
          flutter pub get
          flutter build apk --debug
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: temp_app/build/app/outputs/flutter-apk/app-debug.apk
