name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build
        run: |
          mkdir -p temp_app
          # Remove arquivos conflitantes
          rm -rf temp_app/lib temp_app/pubspec.yaml
          # Copia o código atual para a pasta temporária
          cp -r . temp_app/
          cd temp_app
          flutter pub get
          flutter build apk --debug
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: temp_app/build/app/outputs/flutter-apk/app-debug.apk
