name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Setup project structure
        run: |
          mkdir temp_app
          flutter create temp_app
          # Remove arquivos padrão
          rm -rf temp_app/lib temp_app/pubspec.yaml
          # Copia tudo, exceto a própria pasta temp_app e pastas de controle do git/github
          find . -maxdepth 1 -not -name '.' -not -name 'temp_app' -not -name '.git' -not -name '.github' -exec cp -r {} temp_app/ \;
          
      - name: Build APK
        run: |
          cd temp_app
          flutter pub get
          flutter build apk --release
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
